### ISSUE TITLE
Verifying the response state (without knowing how it is set by the implementation)?

### ISSUE THREAD

**Issue by wu-lee** [danawoodman/sinon-express-mock#12]
As an example of the kind of I'm wanting to do: say I check the return code of a route, something like this:

```
    // Handler definition
   const route = (req, res) => {
        res.send({name: 'foo'}); // implies status 200
    };
```

```
   // Test
   describe('#/api/user', function() {
        it('should get the username', () => {
            const req = mockReq();
            const res = mockRes();
            route(req, res);

            expect(res.statusCode).to.equal(200); // check the return code is 200 OK
            // ...
        });
    });
```

However, the stub request object has no internal state like a real request would.  I don't want to build in the requirement that the  `res#statusCode` method is actually called explicitly (not least because there's a `#status` alias, and possibly other things going on internally). So what I imagine is an extremely common case is difficult to verify.

This generalises to all the other methods of Request and Response objects which return internal state. It looks like the stub objects need to wrap real ones for this to be achievable correctly.

But possibly this has been anticipated and there's an easy workaround that makes `res.statusCode` return 200 by default, or something else if a status code was set - just not documented?

**Comment by danawoodman** [comment]
First off, sorry for the very late reply. I don’t actively work on this project and I must have missed the email notification. 

All valid criticism. I don’t use Sinon any more and don’t have time to maintain this module. That said I’m very open to pull requests or adding more maintainers. If this is something you’re interested in, let me know. Going to close for now since I don’t plan on doing this on my own. 🍻
